### ISSUE TITLE
Sign-up confirmation email

### ISSUE THREAD

**Issue by ivanmauricio** [TechforgoodCAST/first-days#12]
A user should receive a confirmation email after they have successfully registered onto the app

relates #7

**Comment by ivanmauricio** [comment]
@GeoffJWCC Could you put the copy for the sign-up confirmation email on this issue? Thanks!

**Comment by GeoffJWCC** [comment]
@ivanmauricio   Please see attached a very draft copy for the sign up confirmation. 
[First days confirmation e-mail Feb 2018.docx](https://github.com/TechforgoodCAST/first-days/files/1685374/First.days.confirmation.e-mail.Feb.2018.docx)

**Comment by GeoffJWCC** [comment]
@ivanmauricio I have made an amendment to the text. See attached.
[First.days.confirmation.e-mail.Feb.2018.1.docx](https://github.com/TechforgoodCAST/first-days/files/1688658/First.days.confirmation.e-mail.Feb.2018.1.docx)
