### ISSUE TITLE
Wales Coop brand guidelines

### ISSUE THREAD

**Issue by nogainbar** [TechforgoodCAST/first-days#14]
Hey @GeoffJWCC!

Would you be able to let me know about the Brand guidelines? 
could you please attach the Brand guidelines here?

thank you!
Noga

**Comment by GeoffJWCC** [comment]
@nogainbar ,   Please see attached brand guidelines as requested. Please get in touch should you have any queries.
[WCC STYLE GUIDE    @@@(5).pdf](https://github.com/TechforgoodCAST/first-days/files/1677493/WCC.STYLE.GUIDE.5.pdf)

**Comment by nogainbar** [comment]
Great @GeoffJWCC, thank you very much!
