### ISSUE TITLE
Change options in 'specific skills' dropdown based on answer to 'role area' question

### ISSUE THREAD

**Issue by ivanmauricio** [TechforgoodCAST/first-days#17]
The options in the 'specific skills' dropdown menu should change based on what they answered for the 'role area'

eg if the user selects 'Legal' as the  'role area' then the specific skills should all be related to legal matters

**Comment by nogainbar** [comment]
Hey @GeoffJWCC, 
would you be able to send us the various options for these fields? so what appears when you choose any of these areas (IT, LEGAL ECT)
Would these options be a single select or multiple select?

Thanx!
Noga

**Comment by GeoffJWCC** [comment]
@ivanmauricio @nogainbar  Morning both,

The drop down options for the Legal, HR and IT skills areas are as follows:

# HR

- Training/staff development
- Policies & procedure
- Appraisals and performance management
- Other

# IT

- Social media/Website development
- CRM/intranet/database development & maintenance
- Software development
- Server maintenance & development
- Other

# Legal

- Governance & legal structures
- Contracts & Agreements
- Advising board members of legal obligations
- Employment Law
- Data protection/GDPR
- Other

Regards


Geoff
